### ISSUE TITLE
Move to DefinititlyTyped

### ISSUE THREAD

**Issue by mfal** [albertkim/reactstrap.d.ts#2]
Hey @albertkim,

nice work so far. Have you ever considered putting your typings to [DefinitlyTyped](http://definitelytyped.org)? So typings can evolve independently and one can easily install typings with

`[npm|yarn] i @types/reactstrap`

If you need help with, leave me a PM!

**Comment by mfal** [comment]
It's now on DT

**Comment by albertkim** [comment]
hey @mfal sorry for seeing the notification (I had them turned off 😞). Thanks so much for putting it on there. Could you point me to an up-to-date resource that can teach me about contributing to a DT repository? I would like to improve it, especially as other people appear to be using it.
